<tr id="god[field:id/]">
<td><a href='my_makearchives.php?aid=[field:id/]' title='issue'><img src='images/issue.gif'></a></td>	
<td id="id[field:id/]" title="[field:id/]">[field:id/]</td>
<td id="typeid[field:id/]" title="[field:typeid/]">[field:typeid/]</td>
<td id="litpic[field:id/]" title="[field:litpic/]"><img src="[field:litpic/]" id="ilitpic[field:id/]"></td>
<td id="title[field:id/]" title="[field:title/]">[field:title/]</td>
<td id="market[field:id/]" title="[field:market/]">[field:market/]</td>
<td id="price[field:id/]" title="[field:id/]" >[field:id/]</td>
<td id="stock[field:id/]" title="[field:stock/]">[field:stock/]</td>
<td id="typ[field:id/]" title="[field:typ/]" >[field:typ/]</td>
<td id="trade[field:id/]" title="[field:trade/]">[field:trade/]</td></tr>