<li class="">
    <div class="productListBox">
    <div class="listImg">
    <a href="[field:arcurl/]" target="_blank" title="[field:title/]">
    <img src="[field:litpic/]" alt="[field:title/]"></a></div>
    <div class="listWrap"><strong>￥[field:price/]</strong><del>￥[field:market/]</del>
    </div>
    <div class="listText"><a href="" target="_blank" title="">[field:title/]</a>
    </div>
    <div class="listStar"><span>总销量:<strong>[field:trade/]</strong></span>
    </div>
    <div class="listWrapBtn">
    <a href="javascript:addToCart([field:id/])" class="wrapBtn1">放入购物车</a>
    <a href="[field:arcurl/]" target="_blank" class="wrapBtn2">购买</a></div>
    </div>
    </li>
    </li>