<dl>
<dt><a href="[field:arcurl/]" target="_blank" title="[field:title/]">
<img src="" alt="[field:title/]"></a></dt>
<dd>
<p><a href="[field:arcurl/]" target="_blank" title="">[field:title/]</a></p>
<div class="price_wrap"><strong><span>￥[field:price/]</span></strong><del>￥[field:market/]</del></div>
<div class="btn_wrap"><a href="[field:arcurl/]" target="_blank" class="btn_buy">购买</a></div>
</dd>
</dl>