<?php
$z[0]=Array("list","\r\n<tr id=\"god[field:id/]\">\r\n<td><a href='my_makearchives.php?aid=[field:id/]' title='issue'><img src='images/issue.gif'></a></td>	\r\n<td id=\"id[field:id/]\" title=\"[field:id/]\">[field:id/]</td>\r\n<td id=\"typeid[field:id/]\" title=\"[field:typeid/]\">[field:typeid/]</td>\r\n<td id=\"litpic[field:id/]\" title=\"[field:litpic/]\"><img src=\"[field:litpic/]\" id=\"ilitpic[field:id/]\"></td>\r\n<td id=\"title[field:id/]\" title=\"[field:title/]\">[field:title/]</td>\r\n<td id=\"market[field:id/]\" title=\"[field:market/]\">[field:market/]</td>\r\n<td id=\"price[field:id/]\" title=\"[field:id/]\" >[field:id/]</td>\r\n<td id=\"stock[field:id/]\" title=\"[field:stock/]\">[field:stock/]</td>\r\n<td id=\"typ[field:id/]\" title=\"[field:typ/]\" >[field:typ/]</td>\r\n<td id=\"trade[field:id/]\" title=\"[field:trade/]\">[field:trade/]</td></tr>\r\n",472,1300);
$z[0][4]['pagesize']="50";
$z[1]=Array("pagelist","",1391,1468);
$z[1][4]['listitem']="info,index,end,pre,next,pageno,option";
$z[1][4]['listsize']="5";

?>