<?php
$z[0]=Array("field","",305,323);
$z[0][4]['name']="title";
$z[1]=Array("global","",324,349);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("field","",390,415);
$z[2][4]['name']="words";
$z[3]=Array("field","",455,506);
$z[3][4]['name']="descr";
$z[3][4]['function']="html2text(@me)";
$z[4]=Array("global","",557,588);
$z[4][4]['name']="cfg_templets_skin";
$z[5]=Array("global","",654,685);
$z[5][4]['name']="cfg_templets_skin";
$z[6]=Array("global","",749,780);
$z[6][4]['name']="cfg_templets_skin";
$z[7]=Array("include","",816,851);
$z[7][4]['filename']="head2.htm";
$z[8]=Array("field","",918,946);
$z[8][4]['name']="position";
$z[9]=Array("arclist","\r\n<dl>\r\n<dt><a href=\"[field:arcurl/]\" target=\"_blank\" title=\"[field:title/]\">\r\n<img src=\"\" alt=\"[field:title/]\"></a></dt>\r\n<dd>\r\n<p><a href=\"[field:arcurl/]\" target=\"_blank\" title=\"\">[field:title/]</a></p>\r\n<div class=\"price_wrap\"><strong><span>￥[field:price/]</span></strong><del>￥[field:market/]</del></div>\r\n<div class=\"btn_wrap\"><a href=\"[field:arcurl/]\" target=\"_blank\" class=\"btn_buy\">购买</a></div>\r\n</dd>\r\n</dl>\r\n",4399,4880);
$z[9][4]['flag']="c";
$z[9][4]['titlelen']="38";
$z[9][4]['row']="5";
$z[10]=Array("list","\r\n    <li class=\"\">\r\n    <div class=\"productListBox\">\r\n    <div class=\"listImg\">\r\n    <a href=\"[field:arcurl/]\" target=\"_blank\" title=\"[field:title/]\">\r\n    <img src=\"[field:litpic/]\" alt=\"[field:title/]\"></a></div>\r\n    <div class=\"listWrap\"><strong>￥[field:price/]</strong><del>￥[field:market/]</del>\r\n    </div>\r\n    <div class=\"listText\"><a href=\"\" target=\"_blank\" title=\"\">[field:title/]</a>\r\n    </div>\r\n    <div class=\"listStar\"><span>总销量:<strong>[field:trade/]</strong></span>\r\n    </div>\r\n    <div class=\"listWrapBtn\">\r\n    <a href=\"javascript:addToCart([field:id/])\" class=\"wrapBtn1\">放入购物车</a>\r\n    <a href=\"[field:arcurl/]\" target=\"_blank\" class=\"wrapBtn2\">购买</a></div>\r\n    </div>\r\n    </li>\r\n    </li>\r\n    ",6139,6917);
$z[10][4]['pagesize']="8";
$z[11]=Array("pagelist","",6977,7054);
$z[11][4]['listitem']="info,index,end,pre,next,pageno,option";
$z[11][4]['listsize']="5";
$z[12]=Array("include","",7101,7137);
$z[12][4]['filename']="footer.htm";

?>