<?php  exit();
/*
Page: /listen/app2/msm.php?mob=1111&cod=1111
Error: SunCms错误警告：<font color='red'>连接数据库失败，可能数据库密码不对或数据库服务器出错！</font>
Time2016-04-08 11:45:46
*/
?>
<?php  exit();
/*
Page: /listen/app2/msm.php?mob=1111&cod=1111
Error: SunCms错误警告：<font color='red'>连接数据库失败，可能数据库密码不对或数据库服务器出错！</font>
Time2016-04-08 11:48:17
*/
?>
<?php  exit();
/*
Page: /listen/app2/msm.php?mob=1111&cod=1111
Error: SunCms错误警告：<font color='red'>连接数据库失败，可能数据库密码不对或数据库服务器出错！</font>
Time2016-04-08 11:49:18
*/
?>
<?php  exit();
/*
Page: /listen/app2/msm.php?mob=1111&cod=1111
Error: SunCms错误警告：<font color='red'>连接数据库失败，可能数据库密码不对或数据库服务器出错！</font>
Time2016-04-08 11:49:24
*/
?>
<?php  exit();
/*
Page: /listen/app2/msm.php?mob=1111&cod=1111
Error: SunCms错误警告：<font color='red'>连接数据库失败，可能数据库密码不对或数据库服务器出错！</font>
Time2016-04-08 11:49:32
*/
?>
<?php  exit();
/*
Page: /listen/sms/msm.php?mob=1111&cod=1111
Error: SunCms错误警告：<font color='red'>连接数据库失败，可能数据库密码不对或数据库服务器出错！</font>
Time2016-04-08 11:50:42
*/
?>
<?php  exit();
/*
Page: /listen/sms/msm.php?mob=1111&cod=1111
Error: SunCms错误警告：<font color='red'>连接数据库失败，可能数据库密码不对或数据库服务器出错！</font>
Time2016-04-08 11:53:57
*/
?>
<?php  exit();
/*
Page: /listen/sms/msm.php?mob=1111&cod=1111
Error: SunCms错误警告：<font color='red'>连接数据库失败，可能数据库密码不对或数据库服务器出错！</font>
Time2016-04-08 19:57:46
*/
?>
<?php  exit();
/*
Page: /listen/user/verify.php
Error: SunCms错误警告：<font color='red'>连接数据库失败，可能数据库密码不对或数据库服务器出错！</font>
Time2016-04-21 21:25:19
*/
?>
